[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
include_trailing_comma = true

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
select = ["B", "C", "E", "F", "W", "B9", "S"]
exclude = [".git", ".venv", "build", "dist", "__pycache__"]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["B", "S"]
extend-ignore = ["E203", "W503"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
show_error_codes = true

[tool.bandit]
skips = ["B101"]
exclude = ["tests"]
